[package]
name = "wallpaper"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = "0.12.19"
bincode = "2.0.1"
termion = "4.0.5"
qrcode = "0.14.1"
tokio = { version = "1.45.1", features = ["full"] }
